### ISSUE TITLE
Health check endpoint returns `application/json` content type

### ISSUE THREAD

**Issue by thbishop-intuit** [cello-proj/cello#148]

**Comment by bobstrecansky** [comment]
What `content-type` should this healthcheck endpoint return?

**Comment by jk-intuit** [comment]
https://github.com/cello-proj/cello/blob/1393854a8b6f6d5213f694e2a3b52b4282b600d7/service/handlers.go#L95

Should be changed to `text/plain`

**Comment by bobstrecansky** [comment]
I'll work on this.

**Comment by bobstrecansky** [comment]
I've started a draft PR for this:

https://github.com/cello-proj/cello/pull/367
